In [1]:
import numpy as np
import pandas as pd
import requests
import os
from dotenv import load_dotenv

In [2]:
load_dotenv()
API_KEY = os.getenv("API_KEY")

url = "https://api.coingecko.com/api/v3/coins/markets"

In [3]:
params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 100,
    "page": 1,
    "sparkline": False
}

headers = {
    "x-cg-demo-api-key": API_KEY
}

In [4]:
response = requests.get(url, params=params, headers=headers)

print(response)
print(response.status_code)
print(response.text)

<Response [200]>
200

In [5]:
data = response.json()

df = pd.DataFrame(data)

print(df.shape)

df.head()

(100, 26)

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,64510.000000,1293172494784,1,1293172494784,2.705876e+10,65469.000000,...,2.004640e+07,21000000.0,126080.000,-48.83367,2025-10-06T18:57:42.558Z,67.810000,9.503553e+04,2013-07-06T00:00:00.000Z,None,2026-06-22T16:42:19.838Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1736.400000,209587832767,2,209587832767,1.520608e+10,1773.960000,...,1.206839e+08,NaN,4946.050,-64.89311,2025-08-24T19:21:03.333Z,0.432979,4.009366e+05,2015-10-20T00:00:00.000Z,"{'times': 34.97276661535757, 'currency': 'btc'...",2026-06-22T16:42:19.986Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.998889,186229035578,3,191689888614,4.737542e+10,0.999029,...,1.919036e+11,NaN,1.320,-24.49943,2018-07-24T00:00:00.000Z,0.572521,7.448171e+01,2015-03-02T00:00:00.000Z,None,2026-06-22T16:42:19.400Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,592.700000,79897990799,4,79897990799,6.223859e+08,601.170000,...,1.347832e+08,200000000.0,1369.990,-56.73671,2025-10-13T08:41:24.131Z,0.039818,1.488443e+06,2017-10-19T00:00:00.000Z,None,2026-06-22T16:42:19.019Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999729,74652947255,5,74689620221,1.053338e+10,1.000000,...,7.470441e+10,NaN,1.043,-4.19092,2018-11-15T00:00:00.000Z,0.877647,1.391075e+01,2023-03-11T08:02:13.981Z,None,2026-06-22T16:42:18.909Z

In [6]:
keep_cols = [
    "id",
    "symbol",
    "name",
    "current_price",
    "market_cap",
    "market_cap_rank",
    "total_volume",
    "price_change_percentage_24h",
    "circulating_supply",
    "last_updated"
]

silver_df = df[keep_cols].copy()

silver_df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,last_updated
0,bitcoin,btc,Bitcoin,64510.000000,1293172494784,1,2.705876e+10,0.74717,2.004640e+07,2026-06-22T16:42:19.838Z
1,ethereum,eth,Ethereum,1736.400000,209587832767,2,1.520608e+10,0.76793,1.206839e+08,2026-06-22T16:42:19.986Z
2,tether,usdt,Tether,0.998889,186229035578,3,4.737542e+10,0.00478,1.864367e+11,2026-06-22T16:42:19.400Z
3,binancecoin,bnb,BNB,592.700000,79897990799,4,6.223859e+08,0.66677,1.347832e+08,2026-06-22T16:42:19.019Z
4,usd-coin,usdc,USDC,0.999729,74652947255,5,1.053338e+10,-0.00695,7.466773e+10,2026-06-22T16:42:18.909Z

In [7]:
silver_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           100 non-null    object
 1   symbol                       100 non-null    object
 2   name                         100 non-null    object
 3   current_price                100 non-null    float64
 4   market_cap                   100 non-null    int64
 5   market_cap_rank              100 non-null    int64
 6   total_volume                 100 non-null    float64
 7   price_change_percentage_24h  100 non-null    float64
 8   circulating_supply           100 non-null    float64
 9   last_updated                 100 non-null    object
dtypes: float64(4), int64(2), object(4)
memory usage: 7.9+ KB

In [8]:
silver_df["last_updated"] = pd.to_datetime(silver_df["last_updated"])

In [9]:
silver_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           100 non-null    object
 1   symbol                       100 non-null    object
 2   name                         100 non-null    object
 3   current_price                100 non-null    float64
 4   market_cap                   100 non-null    int64
 5   market_cap_rank              100 non-null    int64
 6   total_volume                 100 non-null    float64
 7   price_change_percentage_24h  100 non-null    float64
 8   circulating_supply           100 non-null    float64
 9   last_updated                 100 non-null    datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(4), int64(2), object(3)
memory usage: 7.9+ KB

In [10]:
from datetime import datetime

silver_df["fetch_time"] = datetime.now()

In [11]:
silver_df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,last_updated,fetch_time
0,bitcoin,btc,Bitcoin,64510.000000,1293172494784,1,2.705876e+10,0.74717,2.004640e+07,2026-06-22 16:42:19.838000+00:00,2026-06-22 22:12:57.090263
1,ethereum,eth,Ethereum,1736.400000,209587832767,2,1.520608e+10,0.76793,1.206839e+08,2026-06-22 16:42:19.986000+00:00,2026-06-22 22:12:57.090263
2,tether,usdt,Tether,0.998889,186229035578,3,4.737542e+10,0.00478,1.864367e+11,2026-06-22 16:42:19.400000+00:00,2026-06-22 22:12:57.090263
3,binancecoin,bnb,BNB,592.700000,79897990799,4,6.223859e+08,0.66677,1.347832e+08,2026-06-22 16:42:19.019000+00:00,2026-06-22 22:12:57.090263
4,usd-coin,usdc,USDC,0.999729,74652947255,5,1.053338e+10,-0.00695,7.466773e+10,2026-06-22 16:42:18.909000+00:00,2026-06-22 22:12:57.090263

In [12]:
silver_df.isnull().sum()

id                             0
symbol                         0
name                           0
current_price                  0
market_cap                     0
market_cap_rank                0
total_volume                   0
price_change_percentage_24h    0
circulating_supply             0
last_updated                   0
fetch_time                     0
dtype: int64

In [13]:
silver_df["price_change_percentage_24h"] = (silver_df["price_change_percentage_24h"].fillna(0))

In [14]:
import sqlite3

conn = sqlite3.connect("../database/crypto.db")

In [15]:
silver_df.to_sql(
    "crypto_market",
    conn,
    if_exists="append",
    index=False
)

conn.close()

In [16]:
# Market Dominance Analysis

market_share = (silver_df[["name", "market_cap"]].copy())

market_share["market_share_percent"] = (
    market_share["market_cap"]
    / market_share["market_cap"].sum()
) * 100

market_share.sort_values(
    "market_share_percent",
    ascending=False
).head(10)

           name     market_cap  market_share_percent
0       Bitcoin  1293172494784             57.771582
1      Ethereum   209587832767              9.363191
2        Tether   186229035578              8.319653
3           BNB    79897990799              3.569387
4          USDC    74652947255              3.335069
5           XRP    70572867739              3.152794
6        Solana    42149121506              1.882983
7          TRON    31459297296              1.405422
8  Figure Heloc    19408956238              0.867082
9   Hyperliquid    14953641514              0.668044

In [17]:
# Liquidity Analysis

silver_df["liquidity_ratio"] = (silver_df["total_volume"]/ silver_df["market_cap"])

silver_df[["name", "liquidity_ratio"]].sort_values("liquidity_ratio", ascending=False).head(10)

         name  liquidity_ratio
21       USD1         0.265326
2      Tether         0.254393
72     Ethena         0.214536
40  Worldcoin         0.150347
41  Bittensor         0.146447
4        USDC         0.141098
31        Sui         0.133850
62       Aave         0.124126
94      Aptos         0.105548
60       Pepe         0.103751

In [19]:
# Market Breadth

positive = (silver_df["price_change_percentage_24h"] > 0).sum()

negative = (silver_df["price_change_percentage_24h"] < 0).sum()

print("Positive Coins:", positive)
print("Negative Coins:", negative)

Positive Coins: 44
Negative Coins: 51

In [20]:
# Volatility Leaders

silver_df["volatility"] = (silver_df["price_change_percentage_24h"].abs())

silver_df[["name", "volatility"]].sort_values("volatility",ascending=False).head(10)

        name  volatility
76      DeXe    29.59989
22       LAB    14.33600
86   Jupiter     8.16434
27  MemeCore     5.33979
48       OKB     5.25024
77  ​​Stable     4.81557
72    Ethena     4.72895
98       ADI     3.50491
17    Monero     3.42617
12      Rain     3.23898

In [21]:
# Stablecoin Analysis

stablecoins = silver_df[silver_df["symbol"].isin(["usdt", "usdc", "dai"])]

stablecoins[["name", "current_price", "total_volume"]]

      name  current_price  total_volume
2   Tether       0.998889  4.737542e+10
4     USDC       0.999729  1.053338e+10
23     Dai       0.999599  1.455477e+08

# Key Findings

1. Bitcoin remains the dominant market participant.

2. Trading volume is concentrated among a small number of large-cap assets.

3. Stablecoins play a critical role in market liquidity.

4. Several mid-cap assets exhibit unusually high liquidity ratios.

5. Market breadth provides a useful indicator of overall sentiment.

6. Volatility remains elevated in selected assets, creating both opportunity and risk.