In [50]:
import numpy as np
import pandas as pd
import requests
import os
from dotenv import load_dotenv

In [51]:
load_dotenv()
API_KEY = os.getenv("API_KEY")

url = "https://api.coingecko.com/api/v3/coins/markets"

In [52]:
params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 100,
    "page": 1,
    "sparkline": False
}

headers = {
    "x-cg-demo-api-key": API_KEY
}

In [53]:
response = requests.get(url, params=params, headers=headers)

print(response)
print(response.status_code)
print(response.text)

<Response [200]>
200

In [54]:
data = response.json()

df = pd.DataFrame(data)

print(df.shape)

df.head()

(100, 26)

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,63910.000000,1280433085077,1,1280433085077,1.964025e+10,63902.000000,...,2.004550e+07,21000000.0,126080.000,-49.31016,2025-10-06T18:57:42.558Z,67.810000,9.414957e+04,2013-07-06T00:00:00.000Z,None,2026-06-20T15:15:26.978Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1732.720000,209118984324,2,209118984324,7.545902e+09,1733.550000,...,1.206839e+08,NaN,4946.050,-64.96748,2025-08-24T19:21:03.333Z,0.432979,4.000870e+05,2015-10-20T00:00:00.000Z,"{'times': 35.27627691760134, 'currency': 'btc'...",2026-06-20T15:15:27.809Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999089,186267081138,3,191729049795,3.174643e+10,0.999174,...,1.919036e+11,NaN,1.320,-24.49271,2018-07-24T00:00:00.000Z,0.572521,7.449725e+01,2015-03-02T00:00:00.000Z,None,2026-06-20T15:15:27.117Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,585.780000,78922889134,4,78922889134,6.339143e+08,587.830000,...,1.347834e+08,200000000.0,1369.990,-57.24217,2025-10-13T08:41:24.131Z,0.039818,1.471052e+06,2017-10-19T00:00:00.000Z,None,2026-06-20T15:15:27.317Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999824,74922367037,5,74924046397,6.618024e+09,1.000000,...,7.493915e+10,NaN,1.043,-4.18186,2018-11-15T00:00:00.000Z,0.877647,1.392152e+01,2023-03-11T08:02:13.981Z,None,2026-06-20T15:15:26.897Z

In [55]:
keep_cols = [
    "id",
    "symbol",
    "name",
    "current_price",
    "market_cap",
    "market_cap_rank",
    "total_volume",
    "price_change_percentage_24h",
    "circulating_supply",
    "last_updated"
]

silver_df = df[keep_cols].copy()

silver_df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,last_updated
0,bitcoin,btc,Bitcoin,63910.000000,1280433085077,1,1.964025e+10,1.28426,2.004550e+07,2026-06-20T15:15:26.978Z
1,ethereum,eth,Ethereum,1732.720000,209118984324,2,7.545902e+09,1.59166,1.206839e+08,2026-06-20T15:15:27.809Z
2,tether,usdt,Tether,0.999089,186267081138,3,3.174643e+10,-0.00289,1.864367e+11,2026-06-20T15:15:27.117Z
3,binancecoin,bnb,BNB,585.780000,78922889134,4,6.339143e+08,1.48238,1.347834e+08,2026-06-20T15:15:27.317Z
4,usd-coin,usdc,USDC,0.999824,74922367037,5,6.618024e+09,0.00066,7.493747e+10,2026-06-20T15:15:26.897Z

In [56]:
silver_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           100 non-null    object
 1   symbol                       100 non-null    object
 2   name                         100 non-null    object
 3   current_price                100 non-null    float64
 4   market_cap                   100 non-null    int64
 5   market_cap_rank              100 non-null    int64
 6   total_volume                 100 non-null    float64
 7   price_change_percentage_24h  99 non-null     float64
 8   circulating_supply           100 non-null    float64
 9   last_updated                 100 non-null    object
dtypes: float64(4), int64(2), object(4)
memory usage: 7.9+ KB

In [57]:
silver_df["last_updated"] = pd.to_datetime(silver_df["last_updated"])

In [58]:
silver_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           100 non-null    object
 1   symbol                       100 non-null    object
 2   name                         100 non-null    object
 3   current_price                100 non-null    float64
 4   market_cap                   100 non-null    int64
 5   market_cap_rank              100 non-null    int64
 6   total_volume                 100 non-null    float64
 7   price_change_percentage_24h  99 non-null     float64
 8   circulating_supply           100 non-null    float64
 9   last_updated                 100 non-null    datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(4), int64(2), object(3)
memory usage: 7.9+ KB

In [59]:
from datetime import datetime

silver_df["fetch_time"] = datetime.now()

In [60]:
silver_df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,price_change_percentage_24h,circulating_supply,last_updated,fetch_time
0,bitcoin,btc,Bitcoin,63910.000000,1280433085077,1,1.964025e+10,1.28426,2.004550e+07,2026-06-20 15:15:26.978000+00:00,2026-06-20 20:46:21.709905
1,ethereum,eth,Ethereum,1732.720000,209118984324,2,7.545902e+09,1.59166,1.206839e+08,2026-06-20 15:15:27.809000+00:00,2026-06-20 20:46:21.709905
2,tether,usdt,Tether,0.999089,186267081138,3,3.174643e+10,-0.00289,1.864367e+11,2026-06-20 15:15:27.117000+00:00,2026-06-20 20:46:21.709905
3,binancecoin,bnb,BNB,585.780000,78922889134,4,6.339143e+08,1.48238,1.347834e+08,2026-06-20 15:15:27.317000+00:00,2026-06-20 20:46:21.709905
4,usd-coin,usdc,USDC,0.999824,74922367037,5,6.618024e+09,0.00066,7.493747e+10,2026-06-20 15:15:26.897000+00:00,2026-06-20 20:46:21.709905

In [61]:
silver_df.isnull().sum()

id                             0
symbol                         0
name                           0
current_price                  0
market_cap                     0
market_cap_rank                0
total_volume                   0
price_change_percentage_24h    1
circulating_supply             0
last_updated                   0
fetch_time                     0
dtype: int64

In [62]:
silver_df["price_change_percentage_24h"] = (silver_df["price_change_percentage_24h"].fillna(0))

In [63]:
import sqlite3

conn = sqlite3.connect("../database/crypto.db")

In [64]:
silver_df.to_sql(
    "crypto_market",
    conn,
    if_exists="append",
    index=False
)

conn.close()